version: '3.8'
services:
  moro-server:
    image: moro-server
    ports:
      - "8088:8088"  
    depends_on:
      - moro-postgresql

  moro-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=moro
      - POSTGRES_PASSWORD=your_password  # Set your database password here
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"

  moro-client:
    image: moro-client
    depends_on: 
      - moro-server
    
