server:
  port: 8087

websocket:
  server:
    url: wss://moro-server:8088/systemResourceInfo
  client:
    name: moro-client1
    trust-store: classpath:truststore/keystore.p12
    trust-store-password: passw0rd
